### ISSUE TITLE
Figuring out path forward on complicated output sources

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#126]
Consider ``cond-wf-003.cwl``

```cwl
class: Workflow
cwlVersion: v1.2
inputs:
  val: int
  def:
    type: string
    default: "Direct"

steps:

  step1:
    in:
      in1: val
      a_new_var: val
    run: foo.cwl
    when: $(inputs.a_new_var > 2)
    out: [out1]

outputs:
  out1:
    type: string
    outputSource:
      - step1/out1
      - def
    pickValue: first_non_null

requirements:
  InlineJavascriptRequirement: {}
  MultipleInputFeatureRequirement: {}
```

Currently we tie all workflow outputs to a particular step, Galaxy doesn't really have non-step processing of workflows.

Question:
- Are there cases where the outputSource wouldn't correspond to a single input or step outside the context of ``pickValue``? If yes, if there. a simpler test case to work off of that doesn't depend on pickValue.
- My first thought here is that we can convert this output into an expression tool with a single output (or even a no-op step of some sort with a single output). Is that something in cwl-utils (https://github.com/common-workflow-language/cwl-utils) or should it be?

**Comment by jmchilton** [comment]
I found an interesting test case that uses pickValue on the result of one step.

```
class: Workflow
cwlVersion: v1.2
inputs:
  data:
    type: int[]
    default: [1, 2, 3, 4, 5, 6]
  test: boolean

steps:

  step1:
    in:
      in1: data
      a_new_var: test
    run: foo.cwl
    when: $(inputs.a_new_var)
    out: [out1]
    scatter: in1

outputs:
  out1:
    type: string[]
    outputSource: step1/out1
    pickValue: all_non_null

requirements:
  ScatterFeatureRequirement: {}
```

Problem here is very similar, we set the outputs when we create the job - not when the jobs are complete. So we don't have an extension point to pick those values and set a workflow output. Same trick here though of adding a step that takes an input, evaluates the picking, and then setting the output would potentially work.

We could also extend the workflow output logic to encode the delayed picking in the database somehow and just pick when we need to fetch the values. That isn't super clean either.
