### ISSUE TITLE
Run GA4GH gdc_dnaseq_transform workflow.

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#60]
It isn't quite working yet - here are some assembled interesting pieces of the workflow that may be causing problems.

```
IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: workflow_step.workflow_id [SQL: u'INSERT INTO workflow_step (create_time, update_time, workflow_id, subworkflow_id, type, tool_id, tool_version, tool_hash, tool_inputs, tool_errors, position, config, order_index, uuid, label) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('2017-08-06 17:11:40.611716', '2017-08-06 17:11:40.611720', None, 1, 'subworkflow', None, None, None, None, None, <read-only buffer for 0x115a97fb0, size -1, offset 0 at 0x115a97e70>, None, None, '494d856ec0fc453688e8c6d464305d7b', u'metrics_markduplicates')]\n", "err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
```

- [x] Implement and/or test valueFrom literals in workflow steps.
  ```
  - id: picard_validatesamfile_original
    run: ../../tools/picard_validatesamfile.cwl
    in:
      - id: INPUT
        source: samtools_bamtobam/OUTPUT
      - id: VALIDATION_STRINGENCY
        valueFrom: "LENIENT"
    out:
      - id: OUTPUT
  ```
- [x] Implement and/or test scattering over workflows. #51 
   ```
  - id: metrics_pe
    run: metrics.cwl
    scatter: bam
    in:
      - id: bam
        source: picard_sortsam_pe/SORTED_OUTPUT
      - id: db_snp_vcf
        source: db_snp_path
      - id: fasta
        source: reference_fasta_path
      - id: input_state
        valueFrom: "sorted_readgroup"
      - id: parent_bam
        source: bam_path
        valueFrom: $(self.basename)
      - id: thread_count
        source: thread_count
      - id: uuid
        source: uuid
    out:
      - id: merge_sqlite_destination_sqlite
   ```
- [x] Implement basename property in ``valueFrom``
   ```
  - id: picard_sortsam_se
    run: ../../tools/picard_sortsam.cwl
    scatter: INPUT
    in:
      - id: INPUT
        source: bwa_se/OUTPUT
      - id: OUTPUT
        valueFrom: $(inputs.INPUT.basename)
    out:
      - id: SORTED_OUTPUT


  - id: picard_mergesamfiles_pe
    run: ../../tools/picard_mergesamfiles.cwl
    in:
      - id: INPUT
        source: picard_sortsam_pe/SORTED_OUTPUT
      - id: OUTPUT
        source: bam_path
        valueFrom: $(self.basename)
    out:
      - id: MERGED_OUTPUT 

   ```
- [x]  Expose secondaryFiles in ``valueFrom`` 
   ```
  - id: integrity
     run: integrity.cwl
     in:
      - id: bai_path
        source: picard_markduplicates/OUTPUT
        valueFrom: $(self.secondaryFiles[0])
      - id: bam_path
        source: picard_markduplicates/OUTPUT
      - id: input_state
        valueFrom: "markduplicates_readgroups"
      - id: uuid
        source: uuid
     out:
      - id: merge_sqlite_destination_sqlite
   ```
