### ISSUE TITLE
Implement Conformance Test Exposing Secondary Files in valueFrom

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#61]
e.g. from GA4GH challenge 
```
- id: integrity
  run: integrity.cwl
  in:
   - id: bai_path
     source: picard_markduplicates/OUTPUT
     valueFrom: $(self.secondaryFiles[0])
   - id: bam_path
     source: picard_markduplicates/OUTPUT
   - id: input_state
     valueFrom: "markduplicates_readgroups"
   - id: uuid
     source: uuid
  out:
   - id: merge_sqlite_destination_sqlite
```
