### ISSUE TITLE
Run BCBIO Worklfow

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#62]
- [ ] Allow uploading files with secondary files.
   ```
    - id: reference__fasta__base
      secondaryFiles:
      - .fai
      - ^.dict
      type:
        items: File
        type: array
   ```
