### ISSUE TITLE
Type unions with array types do not seem to work currently.

### ISSUE THREAD

**Issue by jmchilton** [common-workflow-lab/galaxy#68]
E.g. bwa tool from #63.

```
  filelist:
    type:
      - "null"
      - File
      - type: array
        items: File
```
